name: Publish on NPM registry
on:
  push:
    branches: [main, develop]
    tags: ['**']
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  lint:
    name: Lint with ESLint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup environment
        uses: ./.github/actions/setup
      - name: Run ESLint
        run: pnpm lint
